services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python init_django.py &&
             gunicorn --config gunicorn.conf.py django_app.wsgi:application"
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - uploads_volume:/app/uploads
    depends_on:
      - web

volumes:
  postgres_data:
  uploads_volume:
