# Generated by Django 4.2.7 on 2025-08-27 19:58

from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=file_upload.models.upload_to)),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("file_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Arquivo Enviado",
                "verbose_name_plural": "Arquivos Enviados",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
